package com.ssp.greendao.dao;

import java.util.List;
import com.ssp.greendao.dao.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "COURSE".
 */
public class Course {

    private Long id;
    /** Not-null value. */
    private String courseName;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient CourseDao myDao;

    private List<StudentCourse> studentCourseList;

    public Course() {
    }

    public Course(Long id) {
        this.id = id;
    }

    public Course(Long id, String courseName) {
        this.id = id;
        this.courseName = courseName;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getCourseDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getCourseName() {
        return courseName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<StudentCourse> getStudentCourseList() {
        if (studentCourseList == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            StudentCourseDao targetDao = daoSession.getStudentCourseDao();
            List<StudentCourse> studentCourseListNew = targetDao._queryCourse_StudentCourseList(id);
            synchronized (this) {
                if(studentCourseList == null) {
                    studentCourseList = studentCourseListNew;
                }
            }
        }
        return studentCourseList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetStudentCourseList() {
        studentCourseList = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
