package com.ssp.greendao.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.ssp.greendao.dao.Question;
import com.ssp.greendao.dao.Option;
import com.ssp.greendao.dao.Answer;

import com.ssp.greendao.dao.QuestionDao;
import com.ssp.greendao.dao.OptionDao;
import com.ssp.greendao.dao.AnswerDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig questionDaoConfig;
    private final DaoConfig optionDaoConfig;
    private final DaoConfig answerDaoConfig;

    private final QuestionDao questionDao;
    private final OptionDao optionDao;
    private final AnswerDao answerDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        questionDaoConfig = daoConfigMap.get(QuestionDao.class).clone();
        questionDaoConfig.initIdentityScope(type);

        optionDaoConfig = daoConfigMap.get(OptionDao.class).clone();
        optionDaoConfig.initIdentityScope(type);

        answerDaoConfig = daoConfigMap.get(AnswerDao.class).clone();
        answerDaoConfig.initIdentityScope(type);

        questionDao = new QuestionDao(questionDaoConfig, this);
        optionDao = new OptionDao(optionDaoConfig, this);
        answerDao = new AnswerDao(answerDaoConfig, this);

        registerDao(Question.class, questionDao);
        registerDao(Option.class, optionDao);
        registerDao(Answer.class, answerDao);
    }
    
    public void clear() {
        questionDaoConfig.getIdentityScope().clear();
        optionDaoConfig.getIdentityScope().clear();
        answerDaoConfig.getIdentityScope().clear();
    }

    public QuestionDao getQuestionDao() {
        return questionDao;
    }

    public OptionDao getOptionDao() {
        return optionDao;
    }

    public AnswerDao getAnswerDao() {
        return answerDao;
    }

}
